In [1]:
import numpy as np
myarray = np.array([[1,2,3,4],[2,4,6,8],[4,5,6,7]])

In [2]:
myarray

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [4, 5, 6, 7]])

In [4]:
flat = myarray.flatten()

In [5]:
flat

array([1, 2, 3, 4, 2, 4, 6, 8, 4, 5, 6, 7])

In [11]:
flat[0]

np.int64(1)

In [8]:
flat[3:6]

array([4, 2, 4])

In [13]:
flat[::3] # every 3rd element

array([1, 4, 6, 5])

array does not make a copy of existing element when we assign it to a different variable (if made changes in different variable array element which is obtained from existing orignal array, orignal variable array element changes as well

In [14]:
v = flat[3:8]

In [15]:
v

array([4, 2, 4, 6, 8])

In [16]:
v[0] = 4444444

In [17]:
v

array([4444444,       2,       4,       6,       8])

In [18]:
flat

array([      1,       2,       3, 4444444,       2,       4,       6,
             8,       4,       5,       6,       7])

as we can see orignal existing array element changes as well

if we dont want this we can use copy method

In [19]:
a = flat[3:8].copy()

In [20]:
a

array([4444444,       2,       4,       6,       8])

In [21]:
a[0] = 6666666

In [22]:
a

array([6666666,       2,       4,       6,       8])

In [23]:
flat

array([      1,       2,       3, 4444444,       2,       4,       6,
             8,       4,       5,       6,       7])

as we can see the flat array element remains the same this time

we can do slicing like this as well

In [24]:
flat[[0,5,8]] # this will give the sliced array with 0,5,8 index of flat array

array([1, 4, 4])

In [25]:
flat[[3,6,1]]

array([4444444,       6,       2])

In [26]:
flat[flat>23] # we will only get elements greater than 23

array([4444444])

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
a = np.array([1.1, 2.2, 3.3],dtype = 'int32')

In [32]:
a

array([1, 2, 3], dtype=int32)

In [33]:
b = np.array([1, 2, 3, 4, 5, 6])

In [34]:
b[b%2 ==0]

array([2, 4, 6])

In [41]:
c = np.arange(1,10)

In [42]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
c.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
flat[flat>50]

array([4444444])