In [1]:
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])

In [2]:
arr.dtype

dtype('int64')

lets change it to int32 this will make it more optimised

In [3]:
arr.astype('int32')

array([1, 2, 3, 4, 5], dtype=int32)

In [4]:
arr.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

or we can just create a new array with different datatype

In [6]:
b =  arr = np.array([1, 2, 3, 4, 5],dtype= 'int32')

In [7]:
b

array([1, 2, 3, 4, 5], dtype=int32)

its depends on use case wherther to use float32 or float64 its not necessary that we always have to use float32 instead of float64 sometimes| it might affect the precision of data 

we can also check the the number of bytes memory used in an array

In [8]:
b.nbytes

20

In [10]:
arr.nbytes

20