lets create an np array

In [1]:
import numpy as np

np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [8]:
a = np.array([[1,2,3],[2,4,6]])# unlike lists all element must have same data type

In [12]:
print(a)
type(a)
a.shape # no of rows and columns

[[1 2 3]
 [2 4 6]]


(2, 3)

## create arrays from scratch

In [7]:
 np.zeros((3,3)) #give the rows and column inside a tuple

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((4,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# set range and generate series of array

In [23]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [26]:
np.linspace(1,100,5) # gives evenly spaced values 

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [28]:
myarray = np.array([[1,2,3,4],[2,4,6,8],[4,5,6,7]])

In [33]:
myarray

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [4, 5, 6, 7]])

In [29]:
myarray.shape

(3, 4)

In [30]:
myarray.size

12

In [31]:
myarray.ndim # 2 / since its a 2D array

2

In [32]:
myarray.dtype # internally stored memory allocated as integer using 64 bits storage space

dtype('int64')

In [38]:
myarray = np.array([[1,2,3,4],[2,4,6,8],[4,5,6,7]] , dtype = 'float32') # we can also change the dtype to float32 or float64

In [39]:
myarray

array([[1., 2., 3., 4.],
       [2., 4., 6., 8.],
       [4., 5., 6., 7.]], dtype=float32)

In [40]:
myarray.shape

(3, 4)

In [41]:
myarray.reshape((4,3)) # we can shange the shape of array aswell 

array([[1., 2., 3.],
       [4., 2., 4.],
       [6., 8., 4.],
       [5., 6., 7.]], dtype=float32)

In [42]:
myarray.reshape((6,2))

array([[1., 2.],
       [3., 4.],
       [2., 4.],
       [6., 8.],
       [4., 5.],
       [6., 7.]], dtype=float32)

total number of elements should be same

In [46]:
myarray.flatten() #flatten the 2d array to 1d

array([1., 2., 3., 4., 2., 4., 6., 8., 4., 5., 6., 7.], dtype=float32)