In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[0][2] # which is similar to list

np.int64(3)

now lets use axis

In [7]:
np.sum(arr,axis = 0) # this will give sum of all the values in each row here 0 refers to row

array([12, 15, 18])

In [8]:
np.sum(arr,axis = 1) # this will give sum of all the values in each column here 1 refers to column

array([ 6, 15, 24])

In [14]:
arr[1][1:3] # just like slicing works in python lists

array([5, 6])

In [26]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [35]:
arr[0:3,0:2] # arr(slicing rows, slicing column)

array([[1, 2],
       [4, 5],
       [7, 8]])

## 3D arrays

In [37]:
arr3D = np.array([
                  
                  [[1, 2, 3],
                   [4, 5, 6]],
                  
                  [[7, 8,  9 ], 
                  [10, 11, 12]]
             
                 ])
 

we have 2 2D array inside an array this is wat 3D array looks like

slicing in 3D array

In [38]:
arr3D[0 , 1 , 2]  # so basically its saying give me from 1st 2d array i.e 0 ; from 2 row of 1st 2d array i.e [4, 5, 6] ; give 3rd element i.e 6

np.int64(6)

In [39]:
arr3D[:, 0 , :] # ':' this means from both 1st and 2nd 2D array , from 1st row of both i.e [1, 2, 3] and  [7, 8,  9 ] , give all values ':'

array([[1, 2, 3],
       [7, 8, 9]])

using this slicing we can change data as well

In [40]:
arr3D[:, 0 , :] = 3

In [41]:
arr3D

array([[[ 3,  3,  3],
        [ 4,  5,  6]],

       [[ 3,  3,  3],
        [10, 11, 12]]])

In [44]:
arr3D[0 , 1 , 2] = 444444

In [45]:
arr3D

array([[[     3,      3,      3],
        [     4,      5, 444444]],

       [[     3,      3,      3],
        [    10,     11,     12]]])